import { INetwork } from "@/types/types";

const alchemyKey = process.env.ALCHEMY_SECRET_KEY;

export const networks : INetwork[]  = [
	{
		id: "worldchain",
		name: "World Chain",
		rpcUrl: `https://worldchain-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "worldcoin-wld",
	},
	{
		id: "shape",
		name: "Shape",
		rpcUrl: `https://shape-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "shape",
	},
	{
		id: "ethereum",
		name: "Ethereum",
		rpcUrl: `https://eth-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "ethereum",
	},
	{
		id: "zksync",
		name: "ZKsync",
		rpcUrl: `https://zksync-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "zksync",
	},
	{
		id: "optimism",
		name: "OP Mainnet",
		rpcUrl: `https://opt-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "optimism",
	},
	{
		id: "polygon",
		name: "Polygon PoS",
		rpcUrl: `https://polygon-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "polygon-ecosystem-token",
	},
	{
		id: "geist",
		name: "Geist",
		rpcUrl: `https://geist-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "geist",
	},
	{
		id: "arbitrum",
		name: "Arbitrum",
		rpcUrl: `https://arb-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "arbitrum",
	},
	{
		id: "starknet",
		name: "Starknet",
		rpcUrl: `https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_7/${alchemyKey}`,
		coingeckoId: "starknet",
	},
	{
		id: "arbitrum-nova",
		name: "Arbitrum Nova",
		rpcUrl: `https://arbnova-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "arbitrum-nova",
	},
	{
		id: "astar",
		name: "Astar",
		rpcUrl: `https://astar-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "astar",
	},
	{
		id: "polygon-zkevm",
		name: "Polygon zkEVM",
		rpcUrl: `https://polygonzkevm-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "polygon-zkevm",
	},
	{
		id: "zetachain",
		name: "ZetaChain",
		rpcUrl: `https://zetachain-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "zetachain",
	},
	{
		id: "fantom",
		name: "Fantom Opera",
		rpcUrl: `https://fantom-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "fantom",
	},
	{
		id: "mantle",
		name: "Mantle",
		rpcUrl: `https://mantle-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "mantle",
	},
	{
		id: "berachain",
		name: "Berachain",
		rpcUrl: `https://berachain-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "berachain",
	},
	{
		id: "blast",
		name: "Blast",
		rpcUrl: `https://blast-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "blast",
	},
	// {
	// 	id: "linea",
	// 	name: "Linea",
	// 	rpcUrl: `https://linea-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "linea",
	// },
	// {
	// 	id: "zora",
	// 	name: "Zora",
	// 	rpcUrl: `https://zora-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "zora",
	// },
	// {
	// 	id: "polynomial",
	// 	name: "Polynomial",
	// 	rpcUrl: `https://polynomial-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "polynomial",
	// },
	// {
	// 	id: "base",
	// 	name: "Base",
	// 	rpcUrl: `https://base-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "base",
	// },
	// {
	// 	id: "scroll",
	// 	name: "Scroll",
	// 	rpcUrl: `https://scroll-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "scroll",
	// },
	// {
	// 	id: "gnosis",
	// 	name: "Gnosis",
	// 	rpcUrl: `https://gnosis-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "gnosis",
	// },
	// {
	// 	id: "frax",
	// 	name: "Frax",
	// 	rpcUrl: `https://frax-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "frax",
	// },
	// {
	// 	id: "bnb",
	// 	name: "BNB Smart Chain",
	// 	rpcUrl: `https://bnb-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "binance-smart-chain",
	// },
	// {
	// 	id: "avalanche",
	// 	name: "Avalanche",
	// 	rpcUrl: `https://avax-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "avalanche-2",
	// },
	// {
	// 	id: "solana",
	// 	name: "Solana",
	// 	rpcUrl: `https://solana-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "solana",
	// },
	// {
	// 	id: "metis",
	// 	name: "Metis",
	// 	rpcUrl: `https://metis-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "metis",
	// },
	// {
	// 	id: "opbnb",
	// 	name: "opBNB",
	// 	rpcUrl: `https://opbnb-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "op-bnb",
	// },
	// {
	// 	id: "crossfi",
	// 	name: "CrossFi",
	// 	rpcUrl: `https://crossfi-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "crossfi",
	// },
	// {
	// 	id: "flow",
	// 	name: "Flow EVM",
	// 	rpcUrl: `https://flow-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "flow",
	// },
	// {
	// 	id: "sei",
	// 	name: "Sei",
	// 	rpcUrl: `https://sei-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "sei",
	// },
	// {
	// 	id: "apechain",
	// 	name: "ApeChain",
	// 	rpcUrl: `https://apechain-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "apechain",
	// },
	// {
	// 	id: "lens",
	// 	name: "Lens",
	// 	rpcUrl: `https://lens-sepolia.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "lens",
	// },
	// {
	// 	id: "soneium",
	// 	name: "Soneium",
	// 	rpcUrl: `https://soneium-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "soneium",
	// },
	// {
	// 	id: "rootstock",
	// 	name: "Rootstock",
	// 	rpcUrl: `https://rootstock-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "rootstock",
	// },
	// {
	// 	id: "lumia",
	// 	name: "Lumia",
	// 	rpcUrl: `https://lumia-prism.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "lumia",
	// },
	// {
	// 	id: "unichain",
	// 	name: "Unichain",
	// 	rpcUrl: `https://unichain-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "unichain",
	// },
	// {
	// 	id: "sonic",
	// 	name: "Sonic",
	// 	rpcUrl: `https://sonic-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "sonic",
	// },
	// {
	// 	id: "xmtp",
	// 	name: "XMTP",
	// 	rpcUrl: `https://xmtp-testnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "xmtp",
	// },
	// {
	// 	id: "abstract",
	// 	name: "Abstract",
	// 	rpcUrl: `https://abstract-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "abstract",
	// },
	// {
	// 	id: "monad",
	// 	name: "Monad",
	// 	rpcUrl: `https://monad-testnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "monad",
	// },
	// {
	// 	id: "degen",
	// 	name: "Degen",
	// 	rpcUrl: `https://degen-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "degen",
	// },
	// {
	// 	id: "settlus",
	// 	name: "Settlus",
	// 	rpcUrl: `https://settlus-septestnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "settlus",
	// },
	// {
	// 	id: "ink",
	// 	name: "Ink",
	// 	rpcUrl: `https://ink-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "ink",
	// },
	// {
	// 	id: "ronin",
	// 	name: "Ronin",
	// 	rpcUrl: `https://ronin-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "ronin",
	// },
];
