import { INetwork } from "@/types/types";

const alchemyKey = process.env.ALCHEMY_SECRET_KEY;

export const networks : INetwork[]  = [
	{
		networkId: "worldchain",
		networkName: "World Chain",
		rpcUrl: `https://worldchain-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "worldcoin-wld",
	},
	{
		networkId: "shape",
		networkName: "Shape",
		rpcUrl: `https://shape-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "shape",
	},
	{
		networkId: "ethereum",
		networkName: "Ethereum",
		rpcUrl: `https://eth-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "ethereum",
	},
	{
		networkId: "zksync",
		networkName: "ZKsync",
		rpcUrl: `https://zksync-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "zksync",
	},
	{
		networkId: "optimism",
		networkName: "OP Mainnet",
		rpcUrl: `https://opt-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "optimism",
	},
	{
		networkId: "polygon",
		networkName: "Polygon PoS",
		rpcUrl: `https://polygon-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "polygon-ecosystem-token",
	},
	{
		networkId: "geist",
		networkName: "Geist",
		rpcUrl: `https://geist-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "geist",
	},
	{
		networkId: "arbitrum",
		networkName: "Arbitrum",
		rpcUrl: `https://arb-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "arbitrum",
	},
	{
		networkId: "starknet",
		networkName: "Starknet",
		rpcUrl: `https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_7/${alchemyKey}`,
		coingeckoId: "starknet",
	},
	{
		networkId: "arbitrum-nova",
		networkName: "Arbitrum Nova",
		rpcUrl: `https://arbnova-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "arbitrum-nova",
	},
	{
		networkId: "astar",
		networkName: "Astar",
		rpcUrl: `https://astar-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "astar",
	},
	{
		networkId: "polygon-zkevm",
		networkName: "Polygon zkEVM",
		rpcUrl: `https://polygonzkevm-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "polygon-zkevm",
	},
	{
		networkId: "zetachain",
		networkName: "ZetaChain",
		rpcUrl: `https://zetachain-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "zetachain",
	},
	{
		networkId: "fantom",
		networkName: "Fantom Opera",
		rpcUrl: `https://fantom-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "fantom",
	},
	{
		networkId: "mantle",
		networkName: "Mantle",
		rpcUrl: `https://mantle-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "mantle",
	},
	{
		networkId: "berachain",
		networkName: "Berachain",
		rpcUrl: `https://berachain-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "berachain",
	},
	{
		networkId: "blast",
		networkName: "Blast",
		rpcUrl: `https://blast-mainnet.g.alchemy.com/v2/${alchemyKey}`,
		coingeckoId: "blast",
	},
	// {
	// 	networkId: "linea",
	// 	networkName: "Linea",
	// 	rpcUrl: `https://linea-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "linea",
	// },
	// {
	// 	networkId: "zora",
	// 	networkName: "Zora",
	// 	rpcUrl: `https://zora-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "zora",
	// },
	// {
	// 	networkId: "polynomial",
	// 	networkName: "Polynomial",
	// 	rpcUrl: `https://polynomial-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "polynomial",
	// },
	// {
	// 	networkId: "base",
	// 	networkName: "Base",
	// 	rpcUrl: `https://base-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "base",
	// },
	// {
	// 	networkId: "scroll",
	// 	networkName: "Scroll",
	// 	rpcUrl: `https://scroll-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "scroll",
	// },
	// {
	// 	networkId: "gnosis",
	// 	networkName: "Gnosis",
	// 	rpcUrl: `https://gnosis-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "gnosis",
	// },
	// {
	// 	networkId: "frax",
	// 	networkName: "Frax",
	// 	rpcUrl: `https://frax-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "frax",
	// },
	// {
	// 	networkId: "bnb",
	// 	networkName: "BNB Smart Chain",
	// 	rpcUrl: `https://bnb-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "binance-smart-chain",
	// },
	// {
	// 	networkId: "avalanche",
	// 	networkName: "Avalanche",
	// 	rpcUrl: `https://avax-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "avalanche-2",
	// },
	// {
	// 	networkId: "solana",
	// 	networkName: "Solana",
	// 	rpcUrl: `https://solana-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "solana",
	// },
	// {
	// 	networkId: "metis",
	// 	networkName: "Metis",
	// 	rpcUrl: `https://metis-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "metis",
	// },
	// {
	// 	networkId: "opbnb",
	// 	networkName: "opBNB",
	// 	rpcUrl: `https://opbnb-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "op-bnb",
	// },
	// {
	// 	networkId: "crossfi",
	// 	networkName: "CrossFi",
	// 	rpcUrl: `https://crossfi-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "crossfi",
	// },
	// {
	// 	networkId: "flow",
	// 	networkName: "Flow EVM",
	// 	rpcUrl: `https://flow-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "flow",
	// },
	// {
	// 	networkId: "sei",
	// 	networkName: "Sei",
	// 	rpcUrl: `https://sei-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "sei",
	// },
	// {
	// 	networkId: "apechain",
	// 	networkName: "ApeChain",
	// 	rpcUrl: `https://apechain-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "apechain",
	// },
	// {
	// 	networkId: "lens",
	// 	networkName: "Lens",
	// 	rpcUrl: `https://lens-sepolia.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "lens",
	// },
	// {
	// 	networkId: "soneium",
	// 	networkName: "Soneium",
	// 	rpcUrl: `https://soneium-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "soneium",
	// },
	// {
	// 	networkId: "rootstock",
	// 	networkName: "Rootstock",
	// 	rpcUrl: `https://rootstock-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "rootstock",
	// },
	// {
	// 	networkId: "lumia",
	// 	networkName: "Lumia",
	// 	rpcUrl: `https://lumia-prism.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "lumia",
	// },
	// {
	// 	networkId: "unichain",
	// 	networkName: "Unichain",
	// 	rpcUrl: `https://unichain-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "unichain",
	// },
	// {
	// 	networkId: "sonic",
	// 	networkName: "Sonic",
	// 	rpcUrl: `https://sonic-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "sonic",
	// },
	// {
	// 	networkId: "xmtp",
	// 	networkName: "XMTP",
	// 	rpcUrl: `https://xmtp-testnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "xmtp",
	// },
	// {
	// 	networkId: "abstract",
	// 	networkName: "Abstract",
	// 	rpcUrl: `https://abstract-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "abstract",
	// },
	// {
	// 	networkId: "monad",
	// 	networkName: "Monad",
	// 	rpcUrl: `https://monad-testnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "monad",
	// },
	// {
	// 	networkId: "degen",
	// 	networkName: "Degen",
	// 	rpcUrl: `https://degen-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "degen",
	// },
	// {
	// 	networkId: "settlus",
	// 	networkName: "Settlus",
	// 	rpcUrl: `https://settlus-septestnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "settlus",
	// },
	// {
	// 	networkId: "ink",
	// 	networkName: "Ink",
	// 	rpcUrl: `https://ink-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "ink",
	// },
	// {
	// 	networkId: "ronin",
	// 	networkName: "Ronin",
	// 	rpcUrl: `https://ronin-mainnet.g.alchemy.com/v2/${alchemyKey}`,
	// 	coingeckoId: "ronin",
	// },
];
